on:
  push:
    branches:
      - staging

name: "[STG] Deploy image to K8S"

jobs:
  deploy:
    environment: example-app-stg
    name: Deploy App to K8S
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-6`" >> $GITHUB_ENV

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:${{vars.ENV}}-${SHORT_SHA} -f ./docker/Dockerfile .
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:${{vars.ENV}}-${SHORT_SHA}
          echo "::set-output name=image::$ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:${{vars.ENV}}-${SHORT_SHA}"

    #  write to helm