on:
  push:
    branches:
      - develop

name: "[DEV] Deploy image to K8S"

jobs:
  deploy:
    environment: example-app-dev
    name: Deploy App to K8S
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: login to docker registry
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{secrets.DOCKERHUB_USERNAME}}
      #     password: ${{secrets.DOCKERHUB_TOKEN}}

      # - name: Add SHORT_SHA env property with commit short sha
      #   run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-6`" >> $GITHUB_ENV

      # - name: Build, tag, and push image to DockerHub
      #   id: build-image
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} 
      #   run: |
      #     # Build a docker container and
      #     # push it to ECR so that it can
      #     # be deployed to ECS.
      #     docker build -t $DOCKERHUB_USERNAME/${{ vars.DOCKERHUB_REPOSITORY }}:${{vars.ENV}}-${SHORT_SHA} -f ./docker/Dockerfile .
      #     docker push $DOCKERHUB_USERNAME/${{ vars.DOCKERHUB_REPOSITORY }}:${{vars.ENV}}-${SHORT_SHA}
      #     echo "::set-output name=image::$DOCKERHUB_USERNAME/${{ vars.DOCKERHUB_REPOSITORY }}:${{vars.ENV}}-${SHORT_SHA}"

      #  write on other github repo
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     path: 'src'
      #     ref: 'main'
      #     persist-credentials: false
      
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     path: 'dest'
      #     ref: 'main'
      #     repository: 'ichhoa129/app-deployment'
      #     token: ${{ secrets.GH_TOKEN }}
      #     fetch-depth: 0
      #     persist-credentials: true

      - name: Checkout app-deployment (if not using cache)
        run: git clone https://github.com/ichhoa129/app-deployment.git --branch main

      - name: Modify value file
        shell: bash
        env:
          # version: ${{ steps.build-image.outputs.image }}
          version: hehe
        run: |
          git clone https://github.com/ichhoa129/app-deployment.git --branch main
          cd app-deployment/helm-chart
          sed -i 's|  tag: .*|  tag: '\"${version}\"|' app-example/values.yaml
          git config --global user.email "test@gmail.com"
          git config --global user.name "test"
          git add . ; git commit -m "Update to version ${version}";git push https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/ichhoa129/app-deployment.git