name: Performance Testing
on:
  workflow_run:
    workflows: ["[STG] Deploy image to K8S"]
    branches:
      - staging
    types: 
      - completed

jobs:
  Performance-test:
    environment: example-app-load-test
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: performance/test-plan.jmx
          args: ''
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
      - name: Analyze Results with Latency Lingo
        uses: latency-lingo/github-action@v0.0.2
        with:
          api-key: ${{ secrets.LATENCY_LINGO_API_KEY }}
          file: result.jtl
          label: Checkout Flow Automated Test Plan
          format: jmeter

  slack-workflow-status:
      if: always()
      name: Post Workflow Status To Slack
      needs:
        - deploy
      runs-on: ubuntu-latest
      permissions:
        actions: 'read'
      steps:
        - name: Post to a Slack channel
          id: slack
          uses: slackapi/slack-github-action@v1.26.0
          with:
            channel-id: ${{ secrets.SLACK_CHANNEL_ID}}
            payload: |
              {
                "text": "GitHub Action performance test result: ${{ Performance-test.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "GitHub Action test performance result: ${{ Performance-test.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    }
                  }
                ]
              }
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
