name: "[EXAMPLE_APP] Run Tests & SonarQube Scan"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  test:
    environment: example-app-sonarqube
    name: Run unit test & Sonarqube scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Build, tag, and push image to DockerHub
        id: build-image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} 
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $DOCKERHUB_USERNAME/${{ vars.DOCKERHUB_REPOSITORY }}:${{vars.ENV}}-${SHORT_SHA} -f ./docker/Dockerfile .
          echo "::set-output name=image::$DOCKERHUB_USERNAME/${{ vars.DOCKERHUB_REPOSITORY }}:${{vars.ENV}}-${SHORT_SHA}"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "npm"
      - name: Tests
        run: |
          cp sonar-project.properties ./sonar-project.properties
          npm install
          npm run test
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
